config/routes.rb
Myproject::Application.routes.draw do
  resources :years

  resources :quarters

  get "pages/index"
  resources :weeks#, only: [:index]

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :days#, only: [:index]
  resources :pages

   root 'pages#index'

  get 'search' => 'days#search'
  get 'summary' => 'days#summary'

  

end

app/models/quarter.rb
class Quarter < ActiveRecord::Base
		belongs_to :user

		def self.search_for(query)
			where('task LIKE :query', query: "%#{query}%")
		end
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :set_quarter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /quarters
  # GET /quarters.json
  def index
    @quarters = current_user.quarters.paginate(page: params[:page], per_page: 4)
    #@quarters = Quarter.all
  end

  # GET /quarters/1
  # GET /quarters/1.json
  def show
  end

  # GET /quarters/new
  def new
    @quarter = Quarter.new
  end

  # GET /quarters/1/edit
  def edit
  end

  # POST /quarters
  # POST /quarters.json
  def create
    @quarter = current_user.quarters.new(quarter_params)

    # @quarter = Quarter.new(quarter_params)

    respond_to do |format|
      if @quarter.save
        format.html { redirect_to quarters_path, notice: 'Quarter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quarter }
      else
        format.html { render action: 'new' }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quarters/1
  # PATCH/PUT /quarters/1.json
  def update
    respond_to do |format|
      if @quarter.update(quarter_params)
        format.html { redirect_to quarters_path, notice: 'Quarter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quarters/1
  # DELETE /quarters/1.json
  def destroy
    @quarter.destroy
    respond_to do |format|
      format.html { redirect_to quarters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quarter
      @quarter = Quarter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quarter_params
      params.require(:quarter).permit(:user_id, :date, :quarter_num, :task, :completed)
    end
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/views/quarters/_form.html.erb
<%= form_for(@quarter) do |f| %>
  <% if @quarter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quarter.errors.count, "error") %> prohibited this quarter from being saved:</h2>

      <ul>
      <% @quarter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
    <%= Time.now %>
</p>

<!--   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date,  :value => Time.now %>
  </div>
  <div class="field">
    <%= f.label :quarter_num %><br>
    <%= f.number_field :quarter_num, :value => ((Time.now.month - 1) / 3) + 1 %>
  </div>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_area :task, :size => "60x10" %>
  </div>
  <div class="field">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quarters/edit.html.erb
<h1>Editing Task Quarter</h1>

<%= render 'form' %>

<%= link_to 'Show', @quarter %> |
<%= link_to 'Back', quarters_path %>

app/views/quarters/index.html.erb
<h1>Tasks for Quarter(s)</h1>


<table class="table">
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Quarter</th>
      <th>Year</th>
      <th>Task(s)</th>
      <th style="text-align: center; ">Completed</th>
      <th>Actions</th>
    </tr>
  </thead>


  <tbody>
    <% @quarters.order("quarter_num desc").each do |quarter| %>
      <tr>
<!--         <td><%= quarter.user_id %></td> -->
        <td class="col-md-1"><%= quarter.quarter_num %></td>
        <td class="col-md-1"><%= quarter.date.strftime("%Y") %></td>
        <td class="col-md-5"><%= simple_format(quarter.task) %></td>
        <td class="col-md-1" style="text-align: center; "><%= check_box_tag :completed, "1", quarter.completed, disabled: true %></td>
        <td class="col-md-5"><%= link_to 'Show', quarter %> | 
        <%= link_to 'Edit', edit_quarter_path(quarter) %> | 
        <%= link_to 'Delete', quarter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @quarters, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>


<%= link_to 'Back'.html_safe, summary_path, {:style=>'float:left;'}  %>

<br>

<%= link_to 'New Quarter', new_quarter_path, :class => "btn btn-primary", :style => "color: #FFF;" %>

app/views/quarters/new.html.erb
<h1>New Task for Quarter</h1>

<%= render 'form' %>

<%= link_to 'Back', quarters_path %>

app/views/quarters/show.html.erb
<h1>Task(s) for Quarter</h1>
<p id="notice"><%= notice %></p>
<!-- <p>
  <strong>User:</strong>
  <%= @quarter.user_id %>
</p> -->

<p>
  <strong>Date:</strong>
  <%= @quarter.date %>
</p>

<p>
  <strong>Quarter Number:</strong>
  <%= @quarter.quarter_num %>
</p>

<p>
  <strong>Task:</strong>
  <%= @quarter.task %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @quarter.completed %>
</p>

<%= link_to 'Edit', edit_quarter_path(@quarter) %> |
<%= link_to 'Back', quarters_path %>