config/routes.rb
Myproject::Application.routes.draw do
  resources :years

  resources :quarters

  get "pages/index"
  resources :weeks#, only: [:index]

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :days#, only: [:index]
  resources :pages

   root 'pages#index'

  get 'search' => 'days#search'
  get 'summary' => 'days#summary'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	belongs_to :user

	def self.search_for(query)
		where('task LIKE :query', query: "%#{query}%")
	end	

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  

  def summary
    # currentweek = xxx
    #@thisweek = Week.where(:user_id => current_user.id )
    #@thisweek = Week.where(:week_num => (Date.today.strftime("%U").to_i), :user_id => current_user.id )

     #@days = current_user.days
     @days = Day.where(:user_id => current_user.id )
     @weeks = Week.where(:user_id => current_user.id )
    #binding.pry
      
  end  

  def search
     @days = Day.search_for(params[:q]).paginate(page: params[:page], per_page: 3).where(:user_id => current_user.id )
     @weeks = Week.search_for(params[:q]).paginate(page: params[:page], per_page: 3).where(:user_id => current_user.id )
     @quarters = Quarter.search_for(params[:q]).paginate(page: params[:page], per_page: 2).where(:user_id => current_user.id )
     @years = Year.search_for(params[:q]).paginate(page: params[:page], per_page: 2).where(:user_id => current_user.id )
  end  

  # GET /days
  # GET /days.json
  def index
    @days = current_user.days.paginate(page: params[:page], per_page: 7)
  end
    #@products = Product.all.paginate(page: params[:page], per_page: 5)
    #find where user_id = current_user
    #@days = Day.where(:user_id => "1")
    #@days = Day.all
  #end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    # # {date: 'asdf', task: 'asdf'}
    # new_params = day_params
    # # {date: 'asdf', task: 'asdf', user_id: 4}
    # new_params[:user_id] = current_user.id
    # @day = Day.new(day_params)

    @day = current_user.days.new(day_params)

    # @movie = Movie.new(movie_params)
    # if @movie.save
    #   redirect_to @movie
    # else
    #   render 'new'
    # end 

    respond_to do |format|
      if @day.save
        format.html { redirect_to days_path, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to days_path, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:user_id,:date, :task, :completed)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Time: <%= Time.now %></p>

<!--   <div class="field">
    <%= f.label :user_id, 'User ID' %><br>
    <%= f.text_field :user_id, :value => current_user.id %>
  </div> -->
  <div class="field">
    <%= f.label :date, "Day for Task" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_area :task, :size => "60x10" %>
  </div>
  <div class="field" type="checkbox">
    <%= f.label :completed %> <span>  </span>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit "Create Task(s)" %>
    <%#= link_to 'Create Task(s)', summary_path, :onclick=>"$('.search_form').submit()"  %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing Task Day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Tasks for Day(s)</h1>


<table class="table">
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Date</th>
      <th>Task(s)</th>
      <th style="text-align: center; ">Completed</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @days.order("date desc").each do |day| %>
      <tr>
<!--         <td><%= day.user_id %></td> -->
        <td class="col-md-2"><%= day.date %></td>
        <td class="col-md-5"><%= simple_format(day.task) %></td>
        <td class="col-md-1" style="text-align: center; "><%= check_box_tag :completed, "1", day.completed, disabled: true %></td>
        <td class="col-md-5"><%= link_to 'Show', day %> | 
        <%= link_to 'Edit', edit_day_path(day) %> | 
        <%= link_to 'Delete', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @days, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>

<%= link_to 'Back'.html_safe, summary_path, {:style=>'float:left;'}  %>

<br>

<%= link_to 'New Day', new_day_path, :class => "btn btn-primary", :style => "color: #FFF;" %>

app/views/days/new.html.erb
<h1>New Task for Day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/oldstuff.html.erb
<!-- <div class="navbar-text pull-right">
<%= link_to 'Home', root_path %> |
<%= link_to 'Day', days_path %> |
<%= link_to 'Week', weeks_path %> 

<span>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</span>
</div>
 -->

app/views/days/search.html.erb
<h1>Search Summary</h1>

<div class="col-md-12" style="padding-left: 0px;">



<h5><u>Tasks by Day</u></h5> 
<%# if @days.length > 0  %>
<% if @days.empty? %>
      <br/>
      <p><i>No search result</i></p>
<% else %>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Task(s)</th>
      <th>Completed</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @days.order("date desc").each do |day| %>
      <tr>
        <td class="col-md-2"><%= day.date %></td>
        <td class="col-md-5"><%= simple_format(day.task) %></td>
        <td class="col-md-1"><%= check_box_tag :completed, "1", day.completed, disabled: true %></td>
        <td class="col-md-2"><%= link_to 'Show', day %> | 
        <%= link_to 'Edit', edit_day_path(day) %> | 
        <%= link_to 'Delete', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @days, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>

<%# end %>
<% end %>
<br/>

<h5><u>Tasks by Week</u></h5> 
 <% if @weeks.empty? %>
        <br/>
           <p><i>No search result</i></p>
  <% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Week</th>
        <th>Task(s)</th>
        <th>Completed</th>
        <th>Actions</th>
     </tr>
    </thead>
      <tbody>

      <% @weeks.order("week_num desc").each do |week| %>
        <tr>
          <td class="col-md-2"><%= week.week_num %></td>
          <td class="col-md-5"><%= simple_format(week.task) %></td>
          <td class="col-md-1"><%= check_box_tag :completed, "1", week.completed, disabled: true %></td>
          <td class="col-md-2"><%= link_to 'Show', week %> |
          <%= link_to 'Edit', edit_week_path(week) %> |
          <%= link_to 'Delete', week, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      
    </tbody>
  </table>
  <%= will_paginate @weeks, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>
  <% end %>


<br/>

<h5><u>Tasks by Quarter</u></h5> 
 <% if @quarters.empty? %>
        <br/>
           <p><i>No search result</i></p>
  <% else %>

  <table class="table">
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Quarter</th>
      <th>Year</th>
      <th>Task(s)</th>
      <th>Completed</th>
      <th>Actions</th>
    </tr>
  </thead>


  <tbody>
    <% @quarters.order("quarter_num desc").each do |quarter| %>
      <tr>
<!--         <td><%= quarter.user_id %></td> -->
        <td class="col-md-1"><%= quarter.quarter_num %></td>
        <td class="col-md-1"><%= quarter.date.strftime("%Y") %></td>
        <td class="col-md-5"><%= quarter.task %></td>
        <td class="col-md-1"><%= check_box_tag :completed, "1", quarter.completed, disabled: true %></td>
        <td class="col-md-2"><%= link_to 'Show', quarter %> | 
        <%= link_to 'Edit', edit_quarter_path(quarter) %> | 
        <%= link_to 'Delete', quarter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @quarters, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>
 <% end %>

<br/>

<h5><u>Tasks by Year</u></h5> 
 <% if @years.empty? %>
        <br/>
           <p><i>No search result</i></p>
  <% else %>

<table class="table">
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Year</th>
      <th>Task(s)</th>
      <th>Completed</th>
      <th>Actions</th>
    </tr>
  </thead>


  <tbody>
    <% @years.order("quarter_num desc").each do |year| %>
      <tr>
<!--         <td><%= year.user_id %></td> -->
        <td class="col-md-2"><%= year.quarter_num %></td>
        <td class="col-md-5"><%= year.task %></td>
        <td class="col-md-1"><%= check_box_tag :completed, "1", year.completed, disabled: true %></td>
        <td class="col-md-2"><%= link_to 'Show', year %> | 
        <%= link_to 'Edit', edit_year_path(year) %> | 
        <%= link_to 'Delete', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @years, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>
  <% end %>

app/views/days/show.html.erb
<h1>Task Day</h1>
<p id="notice"><%= notice %></p>
<!-- <p>
  <strong>User:</strong>
  <%= @day.user_id %>
</p>
 -->
<p>
  <strong>Updated:</strong>
  <%= @day.updated_at %>
</p>

<p>
  <strong>Task:</strong>
  <%= @day.task %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', summary_path %>

app/views/days/summary.html.erb
<h1>Summary <small>(<%= Date.today %>)</small></h1>

<div class="col-md-6" style="padding-left: 0px; padding-right: 30px;">



<h5 style="color:#2F6F9F;"><u><b>Tasks by Day</b></u></h5> 
<%# if @days.length > 0  %>
<% if @days.empty? %>
      <br/>
      <p>Add a new daily tasks</p>
<% else %>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Task(s)</th>
      <th style="text-align: center; ">Completed</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @days.order("date desc").limit(7).each do |day| %>
      <tr>
        <td class="col-md-2"><%= day.date %></td>
        <td class="col-md-3"><%= simple_format(day.task) %></td>
        <td class="col-md-1" style="text-align: center; "><%= check_box_tag :completed, "1", day.completed, disabled: true %></td>
        <td class="col-md-1"><%#= link_to 'Show', day %>

      <%= link_to day, class: "" do %>
          <i class="glyphicon glyphicon-file"></i>
      <% end %>

         | 
        <%#= link_to 'Edit', edit_day_path(day) %> 

      <%= link_to edit_day_path(day), class: "" do %>
          <i class="glyphicon glyphicon-cog"></i>
      <% end %>

        | 
        <%= link_to '', day, method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-remove-circle"  %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%# end %>
<% end %>

<%= link_to 'New Task - Day', new_day_path, :class => "btn btn-primary", :style => "color: #FFF;" %> 
<%= link_to 'See more Tasks'.html_safe, days_path, {:style=>'float:right;'}  %>
</div>
<%# @weeks_old = Week.find_by_week_num(Date.today.strftime("%U").to_i) %>
<!-- # if week != nil, then display -->

<%# if @weeks != nil  %>


<div class="col-md-6" style="padding-left: 0px;">
<h5 style="color:#2F6F9F;"><u><b>Tasks this Week - Week <%= Date.today.strftime("%U").to_i %> (<%=  Date.commercial(2014, Date.today.strftime("%U").to_i) %>)</b></u></h5>

<%# if current_user.try(:superuser?) %>
<%# if @weeks.length > 0  %>
  <% if @weeks.empty? %>
        <br/>
        <p>Add a new weekly tasks</p>
  <% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Week</th>
        <th>Task(s)</th>
        <th style="text-align:center;">Completed</th>
        <th>Actions</th>
     </tr>
    </thead>
      <tbody>

      <% @weeks.order("week_num desc").limit(2).each do |week| %>
        <tr>
          <td class="col-md-1"><%= week.week_num %></td>
          <td class="col-md-3"><%= simple_format(week.task) %></td>
          <td class="col-md-1" style="text-align: center; "><%= check_box_tag :completed, "1", week.completed, disabled: true %></td>
          <td class="col-md-1">

      <%= link_to week, class: "" do %>
          <i class="glyphicon glyphicon-file"></i>
      <% end %>

         | 
        <%#= link_to 'Edit', edit_day_path(day) %> 

      <%= link_to edit_week_path(week), class: "" do %>
          <i class="glyphicon glyphicon-cog"></i>
      <% end %>

        | 
        <%= link_to '', week, method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-remove-circle"  %></td>

      </tr>
      <% end %>
      
    </tbody>
  </table>
  <% end %>

<%# end %>
<%= link_to 'New Task - Week', new_week_path, :class => "btn btn-primary", :style => "color: #FFF;"  %>
<%= link_to 'See more Tasks'.html_safe, weeks_path, {:style=>'float:right;'}  %>
</div>

<!-- <div class="col-md-12"> 
  <div class="col-md-6" style="padding-left: 0px;"> 
    <%#= link_to 'New Task - Day', new_day_path, :class => "btn btn-primary" %> 
    <%#= link_to 'See more Tasks'.html_safe, days_path, {:style=>'float:right;'}  %>
  </div>
  <div class="col-md-6"> 
    <%#= link_to 'New Task - Week', new_week_path, :class => "btn btn-primary"  %>
    <%#= link_to 'See more Tasks'.html_safe, weeks_path, {:style=>'float:right;'}  %>
  </div>


</div> -->