config/routes.rb
Myproject::Application.routes.draw do
  resources :years

  resources :quarters

  get "pages/index"
  resources :weeks#, only: [:index]

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :days#, only: [:index]
  resources :pages

   root 'pages#index'

  get 'search' => 'days#search'
  get 'summary' => 'days#summary'

  

end

app/models/year.rb
class Year < ActiveRecord::Base
	belongs_to :user

	def self.search_for(query)
		where('task LIKE :query', query: "%#{query}%")
	end
	
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /years
  # GET /years.json
  def index
    @years = current_user.years.paginate(page: params[:page], per_page: 4)
    #@years = Year.all
  end

  # GET /years/1
  # GET /years/1.json
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years
  # POST /years.json
  def create
    #@year = Year.new(year_params)
    @year = current_user.years.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to years_path, notice: 'Year was successfully created.' }
        format.json { render action: 'show', status: :created, location: @year }
      else
        format.html { render action: 'new' }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1
  # PATCH/PUT /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to years_path, notice: 'Year was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year.destroy
    respond_to do |format|
      format.html { redirect_to years_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_params
      params.require(:year).permit(:user_id, :date, :quarter_num, :task, :completed)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.erb
<%= form_for(@year) do |f| %>
  <% if @year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
      <% @year.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :value => Time.now%>
  </div>
  <div class="field">
    <%= f.label :quarter_num, "Year" %><br>
    <%= f.number_field :quarter_num, :value => Time.now.year %>
  </div>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_area :task, :size => "60x10" %>
  </div>
  <div class="field">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing Task(s) Year</h1>

<%= render 'form' %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<h1>Tasks for Year(s)</h1>


<table class="table">
  <thead>
    <tr>
<!--       <th>User</th> -->
      <th>Year</th>
      <th>Task(s)</th>
      <th style="text-align: center; ">Completed</th>
      <th>Actions</th>
    </tr>
  </thead>


  <tbody>
    <% @years.order("quarter_num desc").each do |year| %>
      <tr>
<!--         <td><%= year.user_id %></td> -->
        <td class="col-md-2"><%= year.quarter_num %></td>
        <td class="col-md-5"><%= simple_format(year.task) %></td>
        <td class="col-md-1" style="text-align: center; "><%= check_box_tag :completed, "1", year.completed, disabled: true %></td>
        <td class="col-md-5"><%= link_to 'Show', year %> | 
        <%= link_to 'Edit', edit_year_path(year) %> | 
        <%= link_to 'Delete', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @years, :class => "pagination", :style=>'float:right; margin-right: 5%;' %>


<%= link_to 'Back'.html_safe, summary_path, {:style=>'float:left;'}  %>

<br>

<%= link_to 'New year', new_year_path, :class => "btn btn-primary", :style => "color: #FFF;" %>

app/views/years/new.html.erb
<h1>Tasks for Year</h1>

<%= render 'form' %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<h1>Task(s) for Year</h1>
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>User:</strong>
  <%= @year.user_id %>
</p> -->

<p>
  <strong>Date:</strong>
  <%= @year.date %>
</p>

<p>
  <strong>Year:</strong>
  <%= @year.quarter_num %>
</p>

<p>
  <strong>Task:</strong>
  <%= @year.task %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @year.completed %>
</p>

<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>