config/routes.rb
Myproject::Application.routes.draw do
  resources :years

  resources :quarters

  get "pages/index"
  resources :weeks#, only: [:index]

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :days#, only: [:index]
  resources :pages

   root 'pages#index'

  get 'search' => 'days#search'
  get 'summary' => 'days#summary'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plan your Time</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<!-- Bootstrap Mobile first -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<!-- Latest compiled and minified JavaScript -->
<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->

<style>
	h1 {margin-top: 0px;} 
</style>
<!-- Website Favicon -->
<link rel="icon" type="image/x-icon" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/favicon.ico">

<!-- Favicon: Apple iOS devices and Google Android Devices -->
<link rel="apple-touch-icon-precomposed" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">

<!-- IE 10 Metro Tile Icon -->
<meta name="msapplication-TileColor" content="#ffffff" />
<meta name="msapplication-TileImage" content="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">


<!-- Favicon: Everything Else -->
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="apple-touch-icon-precomposed" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png">
<link rel="icon" href="https://s3.amazonaws.com/ImagesforBEWDFinalProject/learn-icon-152-184627.png" sizes="32x32">

<style type="text/css">
      .navbar-inverse {
        background-color: #222;
        
        background-color: #0D2399;
        /*border-color: #080808;*/
      }
      .navbar-inverse .navbar-brand {
        color: #FFF;
/*        color: #777;*/
      }
      .navbar-inverse .navbar-brand:hover,
      .navbar-inverse .navbar-brand:focus {
       /* color: #fff;*/
        color: #777;
        background-color: transparent;
      }
      .navbar-inverse .navbar-text {
        color: #777;
      }
      .navbar-inverse .navbar-nav > li > a {
        color: #FFF;
       /* color: #777;*/
      }
      .navbar-inverse .navbar-nav > li > a:hover,
      .navbar-inverse .navbar-nav > li > a:focus {
        color: #777;
        /*color: #fff;
        */background-color: transparent;
      }
      .navbar-inverse .navbar-nav > .active > a,
      .navbar-inverse .navbar-nav > .active > a:hover,
      .navbar-inverse .navbar-nav > .active > a:focus {
        color: #fff;
        background-color: #080808;
      }
      .navbar-inverse .navbar-nav > .disabled > a,
      .navbar-inverse .navbar-nav > .disabled > a:hover,
      .navbar-inverse .navbar-nav > .disabled > a:focus {
        color: #444;
        background-color: transparent;
      }
      .navbar-inverse .navbar-toggle {
        border-color: #333;
      }
      .navbar-inverse .navbar-toggle:hover,
      .navbar-inverse .navbar-toggle:focus {
        background-color: #333;
      }
      .navbar-inverse .navbar-toggle .icon-bar {
        background-color: #fff;
      }
      .navbar-inverse .navbar-collapse,
      .navbar-inverse .navbar-form {
        border-color: #101010;
      }
      .navbar-inverse .navbar-nav > .open > a,
      .navbar-inverse .navbar-nav > .open > a:hover,
      .navbar-inverse .navbar-nav > .open > a:focus {
        color: #fff;
        background-color: #080808;
      }
      @media (max-width: 767px) {
        .navbar-inverse .navbar-nav .open .dropdown-menu > .dropdown-header {
          border-color: #080808;
        }
        .navbar-inverse .navbar-nav .open .dropdown-menu .divider {
          background-color: #080808;
        }
        .navbar-inverse .navbar-nav .open .dropdown-menu > li > a {
          color: #777;
        }
        .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:hover,
        .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:focus {
          color: #fff;
          background-color: transparent;
        }
        .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a,
        .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:hover,
        .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:focus {
          color: #fff;
          background-color: #080808;
        }
        .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a,
        .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:hover,
        .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:focus {
          color: #444;
          background-color: transparent;
        }
      }
      .navbar-inverse .navbar-link {
        color: #777;
      }
      .navbar-inverse .navbar-link:hover {
        color: #fff;
      }
      .navbar-inverse .btn-link {
        color: #777;
      }
      .navbar-inverse .btn-link:hover,
      .navbar-inverse .btn-link:focus {
        color: #fff;
      }
      .navbar-inverse .btn-link[disabled]:hover,
      fieldset[disabled] .navbar-inverse .btn-link:hover,
      .navbar-inverse .btn-link[disabled]:focus,
      fieldset[disabled] .navbar-inverse .btn-link:focus {
        color: #444;
      }
      a.visited {
         color: #FFFFFF;
      }

   /*   .navbar {
      background: #121974;
      } */
</style>



</head>
<body>


<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" style="margin-left: -2%;">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
 <!--      <ul>
      	<li class="navbar-brand" style="list-style-type:none;"><%= link_to 'Home', root_path %></li>
      </ul> -->
      <!-- <a class="navbar-brand" href="">Brand</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
         <li style="font-size: 125%; font-weight:bold;"><%= link_to 'Summary', summary_path %></li>
        <% else %>
         <li style="font-size: 125%; font-weight:bold;"> <%= link_to 'Welcome', pages_path %></li>
        <% end %>  
        <!-- <li class="active"><%= link_to 'Home', root_path %></li> -->
        <li><%= link_to 'Day', days_path %> </li>
        <li><%= link_to 'Week', weeks_path %> </li>
        <li><%= link_to 'Quarter', quarters_path %> </li>
        <li><%= link_to 'Year', years_path %> </li>
      </ul>
 	
	<!-- <form class="navbar-form navbar-left" role="search">       
       <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form> -->

	<%= form_tag "/search", method: "Get", :class=> "navbar-form navbar-left" do %>
		<div class="form-group">
			<%= text_field_tag :q, params[:q], :id => "search_field", :class => "form-control", :placeholder => "search"   %>
			<%= submit_tag "Search", :class => 'btn btn-default' %>
      <%= link_to 'Clear', summary_path, :class => 'btn btn-default' %>
      
		</div>
	<% end %>


 <% if user_signed_in? %>     
      <ul class="nav navbar-nav navbar-right">
<!--         <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Logged in as <strong><%= current_user.email %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li href="#"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
       <li class="divider"></li>   
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <!--  <li class="divider"></li>
            <li><a href="#">Separated link</a></li> -->
          </ul>
        </li>
<% else %>
	   	<ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
  	    <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
<% end %>
</nav>



<div class="container-fluid">
	<span class="notice" style="color: green;"><%= notice %></span>
	<span class="alert" style="margin-bottom: 0px;"><%= alert %></span>

<%= yield %>

</div>
</body>
</html>